### PR TITLE
Trc mot errors

### LINKED ISSUE #341: If the window is resized and a dataset is opened, it looks as if the dataset is empty although there is data inside
Resize the window to make it thinner, and when opening a dataset it looks as if it were empty, you have to scroll down to see your subjects.

### LINKED ISSUE #342: Unexpected behaviour in frontend if you upload a mot file instead of trc or c3d
I guess it will also happens with any other file. We should reject the file and notify user that only trc and c3d are allowed

### PR DESCRIPTION
**Pull request by AlbertoCasasOrtiz**
- Fixes #341.
- Fixes #342.
- Fixes UX when downloading results.
- First approach to #315.

### CODE REVIEW

**Review by nickbianco — APPROVED** [review]
LGTM.

File: frontend/src/pages/data/SubjectView.tsx [hunk 1]
```diff
@@ -1023,7 +1036,7 @@ const SubjectView = observer((props: SubjectViewProps) => {
                 <div className="dz-message needsclick">
                     <i className="h3 text-muted dripicons-cloud-upload"></i>
                     <h5>
-                        Drop C3D or TRC files here to create trials.
+                        "Drop C3D or TRC files here to create trials. You can also drop MOT files, but they must have a TRC or C3D file associated (same name)."
```
Comment (nickbianco) [inline frontend/src/pages/data/SubjectView.tsx:1039]: Remove the quotes around this help message.

Just noticed this on the `dev` frontend deployment.

**Review by nickbianco — CHANGES_REQUESTED** [review]

File: frontend/src/pages/data/SubjectView.tsx (hunk 1 above)
Comment (AlbertoCasasOrtiz) [reply frontend/src/pages/data/SubjectView.tsx]: Done!
