### PR TITLE
Fixing frontend issues

### LINKED ISSUE #325: When a subject is removed, it does not dissapear fron frontend
Itchanges its type to 404 and status to None

### LINKED ISSUE #326: If you try to create a subject with a name that already exists, it wont be created and no error is shown

### PR DESCRIPTION
**Pull request by AlbertoCasasOrtiz**
- Fix #326 
- Fix #325

### CODE REVIEW

File: frontend/src/pages/data/DatasetView.tsx [hunk 1]
```diff
@@ -338,7 +339,13 @@ const DatasetView = observer((props: DatasetViewProps) => {
                                 alert("Subject name cannot be empty");
                                 return;
                             }
+                            const exists = datasetContents.contents.some(obj => obj.name === subjectName);
+                            if (exists) {
+                                alert("Subject name already exists");
```
Comment (nickbianco) [inline frontend/src/pages/data/DatasetView.tsx:344]: Will this message get shown to users on the frontend? If so, maybe add a bit more detail, e.g., "Subject name already exists! Please choose a new, unique subject name."

**Review by nickbianco — APPROVED** [review]
LGTM! I made one minor suggestion. Feel free to address (or not) and merge.

File: frontend/src/pages/data/DatasetView.tsx (hunk 1 above)
Comment (AlbertoCasasOrtiz) [reply frontend/src/pages/data/DatasetView.tsx]: Sounds better! I also changed the "Subject name cannot be empty" message.
