### PR TITLE
Fixes to frontend related to rehabweek epic issue

### LINKED ISSUE #315: Clarify the process for uploading GRF files in the web app
Currently, the AddBiomechanics web application does not make the process for uploading GRF files very clear to users. We don't have any instructions other than the "Fit Physics" toggle, which is not descriptive.  Also, the drag and drop box only mentions C3D and TRC files, not MOT or STO files containing forces.

Also, if you look at the other pages on the website, the front page mentions ID without saying anything about ground reaction forces. The flow diagram only mentions uploading raw marker data. There are some tips and tricks about ground reaction force files but people may not get to that point.

Image

### LINKED ISSUE #354: Mark "Solve for Muscle Activations" as "experimental" in the web app
For now, until we sort out all of the kinks

### LINKED ISSUE #355: Add "Drop Jump" to list of trial tags

### LINKED ISSUE #356: Remove "Age" tag from the list of subject tags
It is redundant with the "Age" subject metric entry.

### PR DESCRIPTION
**Pull request by AlbertoCasasOrtiz**
- Fixes #355.
- Fixes #356.
- Fixes #354.
- Partially Fixes #315.

### CODE REVIEW

File: frontend/src/components/TagEditor.tsx [hunk 1]
```diff
@@ -110,6 +107,7 @@ const trialOptions: Option[] = [
      { value: 'dance', label: 'Dancing' },
      { value: 'gait_initiation', label: 'Gait Initiation' },
      { value: 'jump', label: 'Jumping' },
+     { value: 'drop_jump', label: 'Drop Jumping' },
```
Comment (nickbianco) [inline frontend/src/components/TagEditor.tsx:110]: I would change the label to just 'Drop Jump'

File: frontend/src/pages/data/SubjectView.tsx [hunk 2]
```diff
@@ -569,7 +590,7 @@ const SubjectView = observer((props: SubjectViewProps) => {
         totalFormElements++;
         if (formCompleteSoFar) {
             formElements.push(<div key="moco" className="mb-3">
-                <label>Solve For Muscle Activations:</label>
+                <label>Solve For Muscle Activations (Experimental):</label>
```
Comment (nickbianco) [inline frontend/src/pages/data/SubjectView.tsx:593]: I've actually changed my mind on this one, lets ditch the "Experimental" tag. But could we rename this to "Solve for Muscle Activity"?

**Review by nickbianco — CHANGES_REQUESTED** [review]
Looks good overall! 

I had a few quick comments, including a reversal on the "Solve for Muscle Activations" change.

File: frontend/src/components/TagEditor.tsx (hunk 1 above)
Comment (AlbertoCasasOrtiz) [reply frontend/src/components/TagEditor.tsx]: Done!

File: frontend/src/pages/data/SubjectView.tsx (hunk 2 above)
Comment (AlbertoCasasOrtiz) [reply frontend/src/pages/data/SubjectView.tsx]: Done!

**Review by nickbianco — APPROVED** [review]
LGTM!
